import http from 'node:http';
import type { Ctx } from './context';
import { router, route, Handler } from './router';
import fs from 'node:fs';
import { storeCtx, initCtx } from './context';
import path from 'node:path';
import formidable from 'formidable';
import action from './action';
import { makeId } from './utils';
import { staticVersion, appendedCss, setAppendedCss, setLayout, appendedJs, setAppConfig } from './misc';
import type { Layout, AppConfig } from './misc';
import process from 'node:process'
import 'dotenv/config'
type MiddleWare = (ctx: Ctx, next: Function) => Promise<void>



// static file max-age
const static_age = process.env.NODE_ENV == 'production' ? 3600 : 604800

// call middlewares
let middlewares: MiddleWare[] = []
async function call_middleware(index: number, ctx: Ctx, route_handler: (...args: any) => any) {
    let nextFn
    try {
        if (index >= 0) {
            nextFn = async () => { await call_middleware(index - 1, ctx, route_handler) }
            await middlewares[index](ctx, nextFn)
        }
        else {
            await route_handler(ctx)
        }
    } catch (e) {
        throw e
    }
}
type App = {
    page: (path: string, handler: Handler) => void,
    errorHandler: (ctx: Ctx, e: any) => void,
    use: (fn: MiddleWare) => void,
    htmlErrorHandler: (message: string) => string,
    listen: (port: number) => void,
    setLayout: (fn: Layout) => void,
    setCssFile: (filePath: string) => void

}
let app: App = {
    page: route,
    errorHandler: (ctx: Ctx, e: any) => {
        let message = ''
        if (typeof e == 'object') { // sys generated err
            if (process.env.NODE_ENV == 'development') {
                message = e.message + `\n ${e.stack}`
                console.error(message)
            }
            else {
                message = 'sys error'
            }
        }
        else if (typeof e == 'string') {
            message = e
        }
        if (ctx.req.method == 'POST') {
            // user error, generated by ctx.err()
            if (message.match(/^err:/)) {
                message = message.replace(/^err:/, '')
            }
            // system error
            else {
                console.log(e)
                message = 'system err'
            }
            ctx.json({ err: message })
        }
        else {
            // user error, generated by ctx.err()
            if (message.match(/^err:/)) {
                message = message.replace(/^err:/, '')
            }
            // system error
            else {
                if (process.env.NODE_ENV != 'development') {
                    message = 'system err'
                }
            }
            ctx.res.writeHead(200, {
                'Content-Type': 'text/html',
            });
            ctx.res.end(app.htmlErrorHandler(message))
        }
    },
    htmlErrorHandler: (message: string): string => {
        return `<html><title>Error</title><body><pre>${message}</pre></body></html>`
    },
    use: (fn: MiddleWare) => {
        middlewares.unshift(fn)
    },
    listen: (port: number) => {
        const server = http.createServer(async (req, res) => {
            let appended_elements = []
            // js
            if (req.url == `/main.${staticVersion}.js`) {
                fs.readFile(import.meta.dirname + '/web/frontless.js', function (error, content) {
                    res.writeHead(200, {
                        'Content-Type': 'text/javascript',
                        'Cache-Control': 'public, max-age=' + static_age
                    });
                    res.end(content + appendedJs, 'utf-8');
                })
                return
            }
            // css
            if (req.url == `/main.${staticVersion}.css`) {
                fs.readFile(import.meta.dirname + '/web/frontless.css', function (error, content) {
                    res.writeHead(200, {
                        'Content-Type': 'text/css',
                        'Cache-Control': 'public, max-age=' + static_age
                    });
                    if (error) {
                        res.end('/* error reading frontless.css */', 'utf-8');
                    }
                    else {
                        res.end(content + "\n/* appended css */\n" + appendedCss, 'utf-8');
                    }
                })
                return
            }
            // static
            if (req?.url?.match(/^\/static\/(.+)/)) {
                serve_static(req, res)
                return
            }
            let ctx = initCtx(req, res, app.errorHandler)

            if (req.method == 'POST') {
                const form = formidable({});
                try {
                    let [body, files] = await form.parse(req);
                    ctx.files = files
                    for (let k in body) {
                        let field = body[k]
                        if (Array.isArray(field)) {
                            if (k.match(/\[\]/)) {
                                ctx.body[k.replace('[]', '')] = field.map(f => f.trim())
                            }
                            else {
                                ctx.body[k] = field[0].trim()
                            }
                        }
                        else {
                            ctx.body[k] = field ?? ''
                        }
                    }
                } catch (err) {
                    console.error(err);
                    res.writeHead(400, { 'Content-Type': 'text/plain' });
                    res.end(String(err));
                    return;
                }
            }

            // route
            let pageHandler: () => void
            if (req.url?.match(/\/action\/[\d\w_\-]+\/[\d\w_\-]+/) && req.method == "POST") {
                pageHandler = action
            }
            else {
                let r = router(ctx)
                if (r.matched) {
                    pageHandler = async () => {
                        try {
                            let pageWidget = await r.handler(ctx)
                            ctx.close(pageWidget)
                        } catch (e) {
                            throw e
                        }
                    }
                }
                else {
                    res.writeHead(404, {
                        'Content-Type': 'text/html',
                    });
                    res.end(app.htmlErrorHandler('path not found ' + req.url))
                    return
                }
            }

            storeCtx(ctx, async () => {
                try {
                    await call_middleware(middlewares.length - 1, ctx, pageHandler)
                } catch (e) {
                    if (ctx._sys.isSent) {
                        return
                    }
                    app.errorHandler(ctx, e)
                }
            })

        });

        server.on('clientError', (err, socket) => {
            socket.end('HTTP/1.1 400 Bad Request\r\n\r\n');
        });
        server.listen(port);
        console.log(`listening on port ${port}`)
    },
    setLayout: setLayout,
    setCssFile: (filePath: string) => {
        setAppendedCss(fs.readFileSync(path.resolve(process.cwd(), filePath), { encoding: 'utf8', flag: 'r' }))
    }
}

// append routes based on file path
async function append_route_from_file(file: { path: string, name: string }) {
    let route_path = file.path.replace(/\.js|\.ts$/, '').replace(/^pages\//, '')
    if (route_path == 'index') {
        route_path = ''
    }
    route_path = '/' + route_path
    let handler = await import(process.cwd() + '/' + file.path)
    route(route_path, handler.default)
}

// serve static files from the "static" folder
function serve_static(req: http.IncomingMessage, res: http.ServerResponse) {
    let filePath = process.cwd() + req.url
    fs.readFile(filePath, function (error, content) {
        if (error) {
            res.writeHead(404);
            res.end('file not found')
        }
        else {
            var extname = path.extname(req.url ?? '');
            var contentType = 'unknown';
            switch (extname) {
                case '.html':
                    contentType = 'text/html';
                    break;
                case '.js':
                    contentType = 'text/javascript';
                    break;
                case '.css':
                    contentType = 'text/css';
                    break;
                case '.json':
                    contentType = 'application/json';
                    break;
                case '.png':
                    contentType = 'image/png';
                    break;
                case '.jpg':
                    contentType = 'image/jpg';
                    break;
                case '.wav':
                    contentType = 'audio/wav';
                    break;
                case '.svg':
                    contentType = 'image/svg+xml'
                    break;
            }
            res.writeHead(200, { 'Content-Type': contentType, 'Cache-Control': 'public, max-age=3600' });
            res.end(content, 'utf-8');
        }
    });
}

// export main api
export default function Frontless(config: AppConfig & {
    htmlErrorHandler?: (errMessage: string) => string,
} = {}): App {
    if (typeof config.htmlErrorHandler == 'function') {
        app.htmlErrorHandler = config.htmlErrorHandler
    }
    setAppConfig(config)
    return app
}

export * from './component'
export * from './context'